<div>
    <br>
    <ul>
        <li>Farendløse</li>
        <li>Fjællebro</li>
        <li>Gyrstinge</li>
        <li>Høm</li>
        <li>Jystrup</li>
        <li>Kværkeby</li>
        <li>Nordrup</li>
        <li>Ortved</li>
        <li>Ringsted</li>
        <li>Sneslev</li>
        <li>Vetterslev</li>
        <li>Vigersted</li>
        <li>Ørslev</li>
    </ul>
</div>